groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

- name: terraform-state
  type: gcs
  source:
    bucket: {{terraform_statefile_bucket}}
    json_key: {{gcp_service_account_key}}
    versioned_file: terraform.tfstate

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pivnet-elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
- name: wipe-env
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: wipe-output/*.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
  - task: wipe
    file: pcf-pipelines/install-pcf/gcp/tasks/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_ZONE: {{gcp_zone_1}}

- name: upload-opsman-image
  plan:
  - get: pcf-pipelines
  - get: pivnet-opsmgr
    trigger: true
    params:
      globs:
      - "*GCP.yml"
  - task: upload
    file: pcf-pipelines/install-pcf/gcp/tasks/upload-opsman/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: bootstrap-terraform-state
  serial: true
  plan:
  - get: pcf-pipelines
  - task: create-terraform-state
    params:
      TERRAFORM_STATEFILE_BUCKET: {{terraform_statefile_bucket}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
    file: pcf-pipelines/install-pcf/gcp/tasks/create-initial-terraform-state/task.yml

- name: create-infrastructure
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: create-infrastructure-output/*.tfstate
  plan:
  - aggregate:
    - get: terraform-state
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [upload-opsman-image]
      params:
        globs:
        - "*GCP.yml"
  - task: create-infrastructure
    file: pcf-pipelines/install-pcf/gcp/tasks/create-infrastructure/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_STORAGE_BUCKET_LOCATION: {{gcp_storage_bucket_location}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      POE_SSL_NAME1: {{poe_ssl_name1}}
      POE_SSL_CERT1: {{poe_ssl_cert1}}
      POE_SSL_KEY1: {{poe_ssl_key1}}
      DB_APP_USAGE_SERVICE_USERNAME: {{db_app_usage_service_username}}
      DB_APP_USAGE_SERVICE_PASSWORD: {{db_app_usage_service_password}}
      DB_AUTOSCALE_USERNAME: {{db_autoscale_username}}
      DB_AUTOSCALE_PASSWORD: {{db_autoscale_password}}
      DB_DIEGO_USERNAME: {{db_diego_username}}
      DB_DIEGO_PASSWORD: {{db_diego_password}}
      DB_NOTIFICATIONS_USERNAME: {{db_notifications_username}}
      DB_NOTIFICATIONS_PASSWORD: {{db_notifications_password}}
      DB_ROUTING_USERNAME: {{db_routing_username}}
      DB_ROUTING_PASSWORD: {{db_routing_password}}
      DB_UAA_USERNAME: {{db_uaa_username}}
      DB_UAA_PASSWORD: {{db_uaa_password}}
      DB_CCDB_USERNAME: {{db_ccdb_username}}
      DB_CCDB_PASSWORD: {{db_ccdb_password}}
      DB_ACCOUNTDB_USERNAME: {{db_accountdb_username}}
      DB_ACCOUNTDB_PASSWORD: {{db_accountdb_password}}
      DB_NETWORKPOLICYSERVERDB_USERNAME: {{db_networkpolicyserverdb_username}}
      DB_NETWORKPOLICYSERVERDB_PASSWORD: {{db_networkpolicyserverdb_password}}
      DB_NFSVOLUMEDB_USERNAME: {{db_nfsvolumedb_username}}
      DB_NFSVOLUMEDB_PASSWORD: {{db_nfsvolumedb_password}}
      DB_LOCKET_USERNAME: {{db_locket_username}}
      DB_LOCKET_PASSWORD: {{db_locket_password}}
      DB_SILK_USERNAME: {{db_silk_username}}
      DB_SILK_PASSWORD: {{db_silk_password}}
      DB_CLOUDSQLDB_TIER: {{db_cloudsqldb_tier}}

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [create-infrastructure]
      params: {globs: []}
  - task: check-opsman-dns
    attempts: 3
    file: pcf-pipelines/install-pcf/gcp/tasks/check-opsman-dns/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
  - task: config-opsman-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{opsman_admin_password}}
  - task: configure-director
    file: pcf-pipelines/install-pcf/gcp/tasks/config-director/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_TRUSTED_CERTS: {{opsman_trusted_certs}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [configure-director]
      trigger: true
      params: {globs: []}
  - task: deploy-director
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
