groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master
  
- name: pks-install-pipeline
  type: git
  source:
    uri: https://github.com/JasonMorgan/pks-install-pipeline.git
    branch: master

- name: terraform-state
  type: gcs
  source:
    bucket: {{terraform_statefile_bucket}}
    json_key: {{gcp_service_account_key}}
    versioned_file: terraform.tfstate

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

jobs:
- name: wipe-env
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: wipe-output/*.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
  - task: wipe
    file: pcf-pipelines/install-pcf/gcp/tasks/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_ZONE: {{az_1_name}}

- name: upload-opsman-image
  plan:
  - get: pcf-pipelines
  - get: pivnet-opsmgr
    # trigger: true
    params:
      globs:
      - "*GCP.yml"
  - task: upload
    file: pcf-pipelines/install-pcf/gcp/tasks/upload-opsman/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: bootstrap-terraform-state
  serial: true
  plan:
  - get: pcf-pipelines
  - task: create-terraform-state
    params:
      TERRAFORM_STATEFILE_BUCKET: {{terraform_statefile_bucket}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
    file: pcf-pipelines/install-pcf/gcp/tasks/create-initial-terraform-state/task.yml

- name: create-infrastructure
  serial_groups: [terraform]
  ensure:
    put: terraform-state
    params:
      file: create-infrastructure-output/*.tfstate
  plan:
  - aggregate:
    - get: terraform-state
    - get: pcf-pipelines
    - get: pks-install-pipeline
    - get: pivnet-opsmgr
      passed: [upload-opsman-image]
      params:
        globs:
        - "*GCP.yml"
  - task: create-infrastructure
    file: pks-install-pipeline/ci/deploy-opsman/tasks/create-infrastructure/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{az_1_name}}
      GCP_ZONE_2: {{az_2_name}}
      GCP_ZONE_3: {{az_3_name}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_STORAGE_BUCKET_LOCATION: {{gcp_storage_bucket_location}}
      GCP_ZONE_NAME: {{gcp_zone_name}}
      GCP_DOMAIN: {{gcp_domain}}

- name: configure-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [create-infrastructure]
      params: {globs: []}
  - task: check-opsman-dns
    attempts: 3
    file: pcf-pipelines/install-pcf/gcp/tasks/check-opsman-dns/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
  - task: config-opsman-auth
    file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{opsman_admin_password}}
  - task: configure-director
    file: pcf-pipelines/install-pcf/gcp/tasks/config-director/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_TRUSTED_CERTS: {{opsman_trusted_certs}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_ZONE_1: {{az_1_name}}
      GCP_ZONE_2: {{az_2_name}}
      GCP_ZONE_3: {{az_3_name}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}

- name: deploy-director
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [configure-director]
      trigger: true
      params: {globs: []}
  - task: deploy-director
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
