---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pcf-pipelines 
- name: pivnet-opsmgr
- name: terraform-state
- name: pks-install-pipeline

outputs:
- name: create-infrastructure-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_ZONE_1:
  GCP_ZONE_2:
  GCP_ZONE_3:
  GCP_STORAGE_BUCKET_LOCATION:
  GCP_RESOURCE_PREFIX:
  GCP_ZONE_NAME:
  GCP_DOMAIN: 

run:
  path: pcf-pipelines/install-pcf/gcp/tasks/create-infrastructure/task.sh
